config/routes.rb
Microgigz::Application.routes.draw do

  root :to => 'leads#index'

  resources :leads
  post '/leads/convert_to_project'=>'leads#convert_lead_to_project'
  post '/leads/ajax_request'=>'leads#ajax_request'
  post '/leads/client_creation_form'=> 'leads#client_creation_form'

  resources :projects
  get  '/projects/display_resources'=>'projects#display_resources'
  post  '/projects/get_client_name'=>'projects#get_client_name'

  resources :clients
  post '/clients/client'=>'clients#get_client_names'

  get  '/login/new'=>'login#new'
  get  '/login/signout'=>'login#signout'
  post '/login/auth'=>'login#auth'

  resources :roleassignments, :only => [:index,:assign_role]
  post '/roleassignments/assign_role'=>'roleassignments#assign_role'
  post '/roleassignments/delete_role'=>'roleassignments#delete_role'
  resources :profiles
  resources :resources
  resources :skills
  devise_for :users

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :email, :name, :profileable_id, :profileable_type, :telephone
  belongs_to :profileable, :polymorphic => true

  #NO MORE EXISTS

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile =  Profile.find_by_id(params[:id])
    @client  =  Client.find_by_id(params[:id])



    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create

    @resource = Resource.create()
    @profile = Profile.new(params[:profile])
    @profile.update_attributes(profileable_id:@resource.id,profileable_type:'Resource')

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div class="row">
  <div class="col-lg-12">

    <h1>Listing profiles</h1>

    <table class="table padding_4">
      <caption class="margin_4"></caption>
      <tr class="background_color">
        <th class="color">Name</th>
        <th class="color">Email</th>
        <th class="color">Telephone</th>
        <th class="color">Profileable type</th>
        <th class="color">Profileable</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @profiles.each do |profile| %>
          <tr>
            <td><%= profile.name %></td>
            <td><%= profile.email %></td>
            <td><%= profile.telephone %></td>
            <td><%= profile.profileable_type %></td>
            <td><%= profile.profileable_id %></td>
            <td><%= link_to 'Show', profile ,:class=>"btn btn-default"%></td>
            <td><%= link_to 'Edit', edit_profile_path(profile) ,:class=>"btn btn-default" %></td>
            <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-default" %></td>
          </tr>
      <% end %>
    </table>

  </div>
</div>

<br />

<div class="row">
  <div class="col-lg-12">

    <table>
      <tr>
        <td>
          <%= link_to 'New Lead', new_lead_path,:class=>"btn btn-default" %>
        </td>
        <td>
          <%= link_to 'Profiles', profiles_path,:class=>"btn btn-default" %>
        </td>
        <td>
          <%= link_to 'Projects', projects_path,:class=>"btn btn-default" %>
        </td>
        <td>
          <%= link_to 'Leads', leads_path,:class=>"btn btn-default" %>
        </td>
      </tr>
    </table>

  </div>
</div>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tr>
    <td>
      <b>Name</b>
    </td>
    <td>
      <%= @profile.name %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Email</b>
    </td>
    <td>
      <%= @profile.email %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Telephone</b>
    </td>
    <td>
      <%= @profile.telephone %>
    </td>
  </tr>
  <tr>
    <td>
      <% if @profile.profileable_type == "Client" %>
      <b>Company Name</b>
    </td>
    <td>
      <%=@client.company_name%>
    </td>
  </tr>
  <tr><td></td><td></td></tr>
</table>

<br>

  <tr>
    <td>
      <%= link_to 'Edit', edit_profile_path(@profile),:class=>"btn btn-default" %>
      <%= link_to 'Back', profiles_path ,:class=>"btn btn-default"%>
    </td>
  </tr>
</table>
<% end %>