config/routes.rb
Microgigz::Application.routes.draw do

  root :to => 'leads#index'

  resources :leads
  post '/leads/convert_to_project'=>'leads#convert_lead_to_project'
  post '/leads/ajax_request'=>'leads#ajax_request'
  post '/leads/client_creation_form'=> 'leads#client_creation_form'

  resources :projects
  get  '/projects/display_resources'=>'projects#display_resources'
  post  '/projects/get_client_name'=>'projects#get_client_name'

  resources :clients
  post '/clients/client'=>'clients#get_client_names'

  get  '/login/new'=>'login#new'
  get  '/login/signout'=>'login#signout'
  post '/login/auth'=>'login#auth'

  resources :roleassignments, :only => [:index,:assign_role]
  post '/roleassignments/assign_role'=>'roleassignments#assign_role'
  post '/roleassignments/delete_role'=>'roleassignments#delete_role'
  resources :profiles
  resources :resources
  resources :skills
  devise_for :users

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :company_name, :status,:user
  has_one :user, :as => :userable
  has_many :leads  ,:dependent => :destroy
  has_many :projects ,:dependent => :destroy
  has_many :notes , :as => :noteable
  accepts_nested_attributes_for :user,:allow_destroy => true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
 # load_and_authorize_resource :except => [:show, :edit, :update]

  def index
    @clients = Client.where(status:"Active")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find_by_id(params[:id])
    @user = @client.user
    @leads   =  @client.leads
    @notes = @client.notes
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new
    @user = @client.build_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find_by_id(params[:id])
    @user = @client.user
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.create(company_name:params[:client][:company_name],status:params[:client][:status])
    @user = @client.build_user(params[:client][:user])
    @user.save!
    params[:request_page] = nil

    respond_to do |format|
      if @client.save

        format.js
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find_by_id(params[:id])
    respond_to do |format|
      if @client.update_attributes(:company_name => params[:client][:company_name])
         @user = @client.user.update_attributes(params[:client][:user])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  def get_client_names
    @search = params[:search]
    @user   = Client.select("clients.id").joins(:user).where("clients.id=users.userable_id and users.userable_type='Client' and clients.status='Active' and users.name like '#{params[:search]}%'")
    #under cosideration
  end
end


























#*********************************************************************************************************************************************
#@user   = User.find_by_sql("select c.id, u.name from clients c, users u where u.name like '#{params[:search]}%' and (c.id=u.userable_id and u.userable_type='Client')")
#@user = User.where("name like 'p%' and userable_type='Client'").select("name , userable_id as id")

# Client.joins("INNER JOIN users ON users.userable_id = clients.id and users.userable_type='Client' and clients.status='Active' and users.name like '#{params[:search]}%'")
# User.joins(:account).where("account_users.role = 1 AND accounts.subscription_end_date BETWEEN (NOW() - INTERVAL 8 DAY) AND (NOW() + INTERVAL 4 DAY)
#            AND accounts.account_type = '#{Account::TYPE_FREE}' AND accounts.payment_method = '#{Account::PAYMENT_TRIAL}'")
#@user=Client.joins(:user).where("clients.id=users.userable_id and users.userable_type='Client' and clients.status='Active' and users.name like '#{params[:search]}%'")

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_clients.html.erb
<%if @user.length != 0%>
    <datalist id="items">
      <%@user.each do |client|%>
          <option  value="<%=client.user.name%>"  label="<%=client.id%>"/>
      <%end%>
    </datalist>
<%else%>
    <div id="new_client" class="list-group width_100_percent">
      <a href="#" class="list-group-item" style="border-radius: 0px" onclick="create_client('<%=@search%>');">
        New...
      </a>
    </div>
<%end%>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
    <% if @client.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@client.errors.count, "error") %> prohibited this project from being saved:</h2>
          <ul>
            <% @client.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <%end %>
    <div class="display-block">
      <%= f.label :company_name %>
      <%= f.text_field :company_name,:class=>"form-control" %>
    </div>
    <%= f.fields_for @user do |builder| %>
      <div class="display-block">
       <b>Name</b>
       <br/>
       <%=builder.text_field :name,:class=>"form-control" %>
      </div>
      <div class="display-block">
        <b>Login Id</b>
        <br/>
        <%=builder.text_field :login_id,:class=>"form-control" %>
      </div>
      <div class="display-block">
        <b>Email</b>
        <br/>
        <%=builder.text_field :email,:class=>"form-control" %>
      </div>
      <div class="display-block">
        <b>Telephone</b>
        <br/>
        <%=builder.text_field :telephone,:class=>"form-control" %>
      </div>
      <div class="display-block">
        <b>Password</b>
        <br/>
        <%=builder.password_field :password,:class=>"form-control" %>
      </div>
    <%end%>
    <div class="display-block">
      <%=f.hidden_field :status,:value=>"Active",:class=>"form-control" %>
    </div>
    <br/>
    <div class="display-block">
      <b></b>
      <br/>
      <%=submit_tag("Save", :class => 'btn btn-default') %>
      <%=link_to 'Back', clients_path,:class=>"btn btn-default" %>
    </div>
    <br/>
<%end%>

app/views/clients/_form_edit.html.erb
<%= form_for(@client) do |f| %>
    <% if @client.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@client.errors.count, "error") %> prohibited this project from being saved:</h2>
          <ul>
            <% @client.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <%end %>
    <div class="display-block">
      <%= f.label :company_name %>
      <%= f.text_field :company_name,:class=>"form-control"%>
    </div>
    <%= f.fields_for @user do |builder| %>
      <div class="display-block">
        <%= builder.label :name %>
        <%= builder.text_field :name,:class=>"form-control"%>
      </div>
      <div class="display-block">
        <%= builder.label :login_id %>
        <%= builder.text_field :login_id,:class=>"form-control"%>
      </div>
      <div class="display-block">
        <%= builder.label :email %>
        <%= builder.text_field :email,:class=>"form-control"%>
      </div>
      <div class="display-block">
        <%= builder.label :telephone %>
        <%= builder.text_field :telephone,:class=>"form-control"%>
      </div>
    <%end%>
    <br/>
    <div class="display-block">
      <%=  submit_tag("Update", :class => 'btn btn-default') %>
      <%= link_to 'Back', clients_path,:class=>"btn btn-default" %>
    </div>
    <br/>
<%end%>

app/views/clients/_related_links.html.erb
<h1>Related links of client</h1>

app/views/clients/_sidebar.html.erb
<div>
<%=link_to :Clients,leads_path,:style=>"color:black"%><br>
<%=link_to :Clients,leads_path,:style=>"color:black"%><br>
<%=link_to :Clients,leads_path,:style=>"color:black"%><br>
<%=link_to :Clients,leads_path,:style=>"color:black"%><br>
<%=link_to :Clients,leads_path,:style=>"color:black"%><br>
<%=link_to :Clients,leads_path,:style=>"color:black"%><br>
<%=link_to :Clients,leads_path,:style=>"color:black"%><br>
<%=link_to :Clients,leads_path,:style=>"color:black"%><br>
<%=link_to :Clients,leads_path,:style=>"color:black"%><br>
</div>

app/views/clients/create.js.erb
<% if !params[:request_page].nil?%>
    $("#lead_client_name").val("<%=@user.name%>");
    $("#client_id").val("<%=@client.id%>");
<%end%>

app/views/clients/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Editing client</h1>
  </div>
</div>
<br/>
<div class="row align_center">
  <div class="col-lg-12">
      <%= render 'form_edit' %>
  </div>
</div>

app/views/clients/get_client_names.js.erb
$('#client').html("<%=escape_javascript(render :partial => 'clients') %>");

app/views/clients/index.html.erb
<%=pageHeader("Clients")%>
<div id="page-container">
  <%i = 0%>

  <%@clients.each do |client| %>
      <div id="record" lang="<%=i%>" class="row leads" onmouseover="dsiplay_circle(this);" onmouseout="hide_circle(this);" style="">
        <section class="position_relative">
          <p id="title">
            <span id="active">Active</span>
            <%=link_to("#{client.user.name}",client_path(id:client.id))%>
          </p>
          <p id="description">
            <%=Client.find_by_id(client.id).company_name%>
          </p>
          <section id="edit-destroy-link">
            <div class="dropdown">
              <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">
                <img src="/images/settings.png" height="25" id="<%=i%>" onclick="show_menu(this);" width="25"/>
              </a>
              <ul class="dropdown-menu" onmouseout="hide_block(this);" onmouseover="display_block(this);" id="menu<%=i%>"  role="menu" aria-labelledby="dLabel">
                <li><%=link_to('Edit', edit_client_path(id:client.id))%></li>
                <li><%#=link_to('Destroy', client, method: :delete, data: { confirm: 'Are you sure?' })%></li>
              </ul>
            </div>
          </section>
        </section>
      </div>
      <hr/>
      <%i = i+1%>
  <%end%>
</div>



















<!--<div class="row">
  <div class="col-lg-12">
       <h2>Clients</h2>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-lg-12">
    <table class="table">
        <%# @clients.each do |client| %>
        <tr>
          <td>
            <%#=link_to "#{client.name}",client_path(client.id)%>
          </td>
        </tr>
        <% #end %>
    </table>
  </div>
</div>

<br/>

<table>
  <tr>
    <td>
        <%#= link_to 'New Client', new_client_path,:class=>"btn btn-default" %>
    </td>
  </tr>
</table>



<%#= link_to 'Edit', edit_client_path(client),:class=>"btn btn-default" %>
<%#= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-default" %>

!-->

app/views/clients/new.html.erb
<br/>
<div class="row">
  <div class="col-lg-12">
    <h1>New client</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>

app/views/clients/show.html.erb
<br/><br/>
<div class="list-group border-margin-client-show">
  <li class="list-group-item border-none">
    <h4 class="list-group-item-heading margin-title">Company name</h4>
    <p class="list-group-item-text"><%= @client.company_name %></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Name</h4>
    <p class="list-group-item-text"><%= @user.name %></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Login Id</h4>
    <p class="list-group-item-text"><%=@user.login_id%></p>
    <p class="list-group-item-text">
      <a href="<%#="/clients/"%><%#=@lead.client.id%>"><%#=@lead.client.user.name%></a>
    </p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Telephone</h4>
    <p class="list-group-item-text"><%= @user.telephone %></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Email</h4>
    <p class="list-group-item-text"><%= @user.email%></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Status</h4>
    <p class="list-group-item-text"><%= @client.status%></p>
  </li>
</div>
<br/>
<h2>Leads</h2>
<br/>
<%if @leads.length == 0%>
    <div class="alert alert-info border-radius-0px">
      <h4>There are no leads to display</h4>
    </div>
<%else%>
    <div class="list-group border-margin-client-show">
    <%@leads.each do |lead|%>
      <li class="list-group-item">
        <h4 class="list-group-item-heading margin-title"><%=link_to "#{lead.title}",lead_path(id:lead.id)%></h4>
        <p class="list-group-item-text"><%= lead.description%></p>
      </li>
    <%end%>
    </div>
<%end%>