config/routes.rb
Microgigz::Application.routes.draw do

  root :to => 'leads#index'

  resources :leads
  post '/leads/convert_to_project'=>'leads#convert_lead_to_project'
  post '/leads/ajax_request'=>'leads#ajax_request'
  post '/leads/client_creation_form'=> 'leads#client_creation_form'

  resources :projects
  get  '/projects/display_resources'=>'projects#display_resources'
  post  '/projects/get_client_name'=>'projects#get_client_name'

  resources :clients
  post '/clients/client'=>'clients#get_client_names'

  get  '/login/new'=>'login#new'
  get  '/login/signout'=>'login#signout'
  post '/login/auth'=>'login#auth'

  resources :roleassignments, :only => [:index,:assign_role]
  post '/roleassignments/assign_role'=>'roleassignments#assign_role'
  post '/roleassignments/delete_role'=>'roleassignments#delete_role'
  resources :profiles
  resources :resources
  resources :skills
  devise_for :users

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title,:start_date,:status,:lead_id,:client_id,:pm_id
  belongs_to :lead
  belongs_to :client
  belongs_to :resource

  has_many :notes , :as => :noteable
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
 # load_and_authorize_resource :except => [:show]

  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @lead = Lead.where(status:"Active")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find_by_id(params[:id])
    @lead = Lead.where(status:"Active")
  end

  # POST /projects
  # POST /projects.json
  def create
   @project = Project.new

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find_by_id(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find_by_id(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def get_client_name
  @user = Lead.find_by_id(params[:lead_id]).client.user
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_edit_form.html.erb
<script>
    function find_client_name(x)
    {
        $.ajax({
            url: "/projects/get_client_name",
            type: "get",
            data: "lead_id="+ x.value
        });

    }
</script>

<%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="display-block">
      <%= f.label :title %>
      <%= f.text_field :title,:class=>"form-control"%>
    </div>

    <div class="display-block">
      <%= f.label :start_date %><br/>
      <input type="datetime-local" name="bdaytime"/>
    </div>
    <div class="display-block">
      <%= f.label :pm_id %>
      <select class="form-control">
        <option value="name">name</option>
        <option value="name">name</option>
        <option value="name">name</option>
        <option value="name">name</option>
        <option value="name">name</option>
      </select>
      <%#=select_tag "pm", options_from_collection_for_select(@project_manager, "id", "name"),:class=>"form-control" ,include_blank: true%>
    </div>
    <div class="display-block">
      <%= f.label :lead_id %>
      <%=select_tag "lid", options_from_collection_for_select(@lead, "id", "title"),:onchange=>"find_client_name(this);",:class=>"form-control",include_blank: true%>
    </div>
    <div class="display-block">
      <%= f.label "Client Name" %>
      <%= text_field_tag :client_name,nil,:class=>"form-control",:readonly=>true%></div>
      <%=hidden_field_tag :client_id%>
    </div>
    <br/>
    <div class="display-block">
       <%=f.hidden_field :status,:value=>"Active"%>
    </div>
    <div class="display-block">
      <%= f.submit :Save,:class=>"btn btn-default",:style=>"width:100px" %>
      <%= link_to 'Back', projects_path,:class=>"btn btn-default",:style=>"width:100px" %>
    </div>
    <br/>
<%end%>

app/views/projects/_form.html.erb
<script>

  function find_client_name(x)
  {
      $.ajax({
          url: "/projects/get_client_name",
          type: "get",
          data: "lead_id="+ x.value
      });

  }

</script>

<%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="display-block">
      <%= f.label :title %>
      <%= f.text_field :title,:class=>"form-control"%>
    </div>
    <div class="display-block">
      <%= f.label :Lead %><br/>
      <select class="form-control">
        <option value="name">name</option>
        <option value="name">name</option>
        <option value="name">name</option>
        <option value="name">name</option>
      </select>
    </div>
    <div class="display-block">
      <%= f.label :start_date %><br/>
      <input type="datetime-local" name="bdaytime">
    </div>
    <div class="display-block">
      <%= f.label :pm_name %>
      <select class="form-control">
        <option value="name">name</option>
        <option value="name">name</option>
        <option value="name">name</option>
        <option value="name">name</option>
      </select>
      <%#=select_tag "pm", options_from_collection_for_select(@project_manager, "id", "name"),:class=>"form-control" ,include_blank: true%>
    </div>
    <div class="display-block">
      <%= f.label "Client Name" %>
      <%= text_field_tag :client_name,nil,:class=>"form-control",:readonly=>true%>
      <%=hidden_field_tag :client_id%>
    </div>
    <br/>
    <div class="display-block">
      <%= f.submit :Save,:class=>"btn btn-default" %>
      <%= link_to 'Back', projects_path,:class=>"btn btn-default" %>
    </div>
    <br/>
<%end%>

app/views/projects/_related_links.html.erb
<h1>Related links of projcet</h1>

app/views/projects/_resource_list.html.erb
<%@resources = Resource.wher%>

app/views/projects/_resources.html.erb
<div class="container" style="height: auto;width: 70%;background: #ffffff;position: absolute;top: 10%;left: 15%;box-shadow: 5px 5px 15px #888888">
  <div class="row align_center">
    <div class="col-lg-12">
      <%=image_tag("/images/nextbridge.png" ,:size => "150x150", :alt => "Edit Entry")%>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
       <h3>Listing Resources</h3>
       <br>
       <table class="table">
         <tr>
           <td>
             <h6>Resources</h6>
           </td>
           <td>
             <input type="text" class="form-control">
           </td>
         </tr>
       </table>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div id="list">
        <%=render :partial =>"resource_list"%>
      </div>
    </div>
  </div>

</div>

app/views/projects/_sidebar.html.erb
<div>
<%=link_to :Projects,leads_path,:style=>"color:black"%><br>
<%=link_to :Projects,leads_path,:style=>"color:black"%><br>
<%=link_to :Projects,leads_path,:style=>"color:black"%><br>
<%=link_to :Projects,leads_path,:style=>"color:black"%><br>
<%=link_to :Projects,leads_path,:style=>"color:black"%><br>
<%=link_to :Projects,leads_path,:style=>"color:black"%><br>
<%=link_to :Projects,leads_path,:style=>"color:black"%><br>
<%=link_to :Projects,leads_path,:style=>"color:black"%><br>
<%=link_to :Projects,leads_path,:style=>"color:black"%><br>
</div>

app/views/projects/display_resources.js.erb
$('#ids').html('<%= escape_javascript( render :partial => 'resources')%>');

app/views/projects/edit.html.erb
<h1>Editing project</h1>
<%= render 'edit_form' %>

app/views/projects/get_client_name.js.erb
$("#progress").css("visibility","hidden");
$('#client_name').val('<%=@user.name%>');
$('#client_id').val('<%=@user.userable_id%>');

app/views/projects/index.html.erb
<%=pageHeader("Projects")%>

<div id="page-container">
  <%i = 0%>
  <%@projects.each do |project|%>
      <div id="record" lang="<%=i%>" class="row leads" onmouseover="dsiplay_circle(this);" onmouseout="hide_circle(this);">
        <section class="position_relative">
          <p id="title">
            <span id="active">Active</span>
            <%=link_to("#{project.title}",project_path(id:project.id))%>
            -
            <%=link_to("#{project.client.user.name}",client_path(id:project.client_id))%>
          </p>
          <p id="description">
            <%="this is a project"%>
          </p>
          <section id="edit-destroy-link">
            <div class="dropdown">
              <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">
                <img src="/images/settings.png" height="25" id="<%=i%>" onclick="show_menu(this);" width="25"/>
              </a>
              <ul class="dropdown-menu" onmouseout="hide_block(this);" onmouseover="display_block(this);" id="menu<%=i%>"  role="menu" aria-labelledby="dLabel">
                <li><%=link_to('Edit', edit_project_path(project))%></li>
                <li><%=link_to('Destroy', project, method: :delete, data: { confirm: 'Are you sure?' })%></li>
              </ul>
            </div>
          </section>
        </section>
        <div class="clear-both">
        </div>
      </div>
      <hr/>
      <%i = i+1%>
  <%end%>
</div>

























<%# @projects.each do |project| %>



            <%#= project.title %>
            <%#= project.start_date %>
            <%#@profile = User.find_by_userable_id(project.client_id)%>
            <%#= @profile.name %>
            <%#= project.status %>
            <%#= project.lead_id %>
            <%#= project.client_id %>
            <%#= project.resource_id %>
            <%#= link_to 'Show', project ,:class=>"btn btn-default"%>
            <%#= link_to 'Edit', edit_project_path(project),:class=>"btn btn-default" %>
            <%#= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-default" %>
        <%# end %>

<br />
<div class="row">
  <div class="col-lg-12">
          <%#= link_to 'Leads', leads_path,:class=>"btn btn-default" %>
          <%#= link_to 'New Project', new_project_path,:class=>"btn btn-default" %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1>New project</h1>
      <%= render 'form' %>
  </div>
</div>

app/views/projects/show.html.erb
<%if !notice.blank?%>
    <!--<div class="alert alert-success"><p id="notice"><%#= notice %></p></div> !-->
<%end%>
<% notice = "" %>

<br/><br/>
<div class="list-group border-margin-client-show">
  <li class="list-group-item border-none">
    <h4 class="list-group-item-heading margin-title">Project</h4>
    <p class="list-group-item-text"> <%= @project.title %></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Description</h4>
    <p class="list-group-item-text"> <%= @project.lead.description %></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Start Date</h4>
    <p class="list-group-item-text"> <%= @project.start_date %></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Lead</h4>
    <p class="list-group-item-text"><%=link_to "#{@project.lead.title}",lead_path(id:@project.lead.id)%></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Client</h4>
    <p class="list-group-item-text"><%=link_to "#{@project.client.user.name}",client_path(id:@project.client.id)%></p>
  </li>
</div>