config/routes.rb
Microgigz::Application.routes.draw do

  root :to => 'leads#index'

  resources :leads
  post '/leads/convert_to_project'=>'leads#convert_lead_to_project'
  post '/leads/ajax_request'=>'leads#ajax_request'
  post '/leads/client_creation_form'=> 'leads#client_creation_form'

  resources :projects
  get  '/projects/display_resources'=>'projects#display_resources'
  post  '/projects/get_client_name'=>'projects#get_client_name'

  resources :clients
  post '/clients/client'=>'clients#get_client_names'

  get  '/login/new'=>'login#new'
  get  '/login/signout'=>'login#signout'
  post '/login/auth'=>'login#auth'

  resources :roleassignments, :only => [:index,:assign_role]
  post '/roleassignments/assign_role'=>'roleassignments#assign_role'
  post '/roleassignments/delete_role'=>'roleassignments#delete_role'
  resources :profiles
  resources :resources
  resources :skills
  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability


    def initialize (user)
      user ||= User.new # Guest user


      if user.has_role? :admin # User is Admin
        can :manage, :all

        # User is Normal User
      elsif user.has_role? :manager
        can :read, [Lead]
        can :manage, [Role , UserRole, Project, Client ,Resource]
      else
        cannot :read, [Project, Client, Role , UserRole]
      end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :company_name, :status,:user
  has_one :user, :as => :userable
  has_many :leads  ,:dependent => :destroy
  has_many :projects ,:dependent => :destroy
  has_many :notes , :as => :noteable
  accepts_nested_attributes_for :user,:allow_destroy => true
end

app/models/lead.rb
class Lead < ActiveRecord::Base

  attr_accessible :client_id, :description, :title, :status


  searchable do
    text :title, :boost => 5
    text :description
    time :updated_at
    time :created_at
  end

  belongs_to :client

  has_one :quote  ,:dependent => :destroy
  has_one :project , :dependent => :destroy


end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :description, :noteable_id, :noteable_type
   belongs_to :noteable, :polymorphic => true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :email, :name, :profileable_id, :profileable_type, :telephone
  belongs_to :profileable, :polymorphic => true

  #NO MORE EXISTS

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title,:start_date,:status,:lead_id,:client_id,:pm_id
  belongs_to :lead
  belongs_to :client
  belongs_to :resource

  has_many :notes , :as => :noteable
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :description, :lead_id
  belongs_to :lead
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  attr_accessible :project_id, :availability, :user
  has_one :user, :as => :userable
  has_many :notes , :as => :noteable

  has_many :projects
  has_many :skills
  accepts_nested_attributes_for :user,:allow_destroy => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :user_roles
  has_many :users, :through => :user_roles
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :rating, :resource_id, :technology

  belongs_to :resource
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :telephone, :login_id , :userable_id , :userable_type
  # attr_accessible :title, :body

  belongs_to :userable, :polymorphic => true


  def get_client_name(id)
      User.find_by_userable_id(id).name
  end

  has_many :user_roles, :dependent => :destroy
  has_many :roles, :through => :user_roles



  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end


  def get_user_name(id)
      User.find_by_userable_id(id).name

  end


end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  attr_accessible :role_id, :user_id ,:status

  belongs_to :user
  belongs_to :role
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/advance_datepicker/_datepicker.html.erb
<%=form_tag "#{ controller.controller_name}", :method => :get do %>
<div class="float-left">
    <input type="date" name="start" />
</div>
<div class="float-left">
    <input type="date" name="end">
</div>
<div class="float-left">
  <%= submit_tag "Search", :name => nil ,:style => "width:100px;height:40px",:class=>"form-control" %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav id="navigation" class="navbar navbar-default" role="navigation">
  <div class="container-fluid" >
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle float-right" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="logo" class="float-left">
      <img src="/images/nextbridge.png">
    </div>
    <div id="company-name" class="float-left">
      <h3>Kantoor</h3>
    </div>
    <div id="nav-top-links" class="float-right">
      <ul>
        <% if user_signed_in? %>
            <li><%=link_to current_user.login_id, resource_path(current_user.userable_id)%> |</li>
        <%end%>
            <li><a href="#">Configuration |</a></li>
        <% if user_signed_in? %>
            <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %> </li>
        <%else%>
            <li><%=link_to :Login ,login_new_path%></li>
        <%end%>
      </ul>
    </div>
    <div class="clear-both"></div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div  class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%=link_to :Leads,leads_path,:class => is_active?("leads")%></li>
        <li><%=link_to :Projects,projects_path,:class => is_active?("projects")%></li>
        <li><%=link_to :Resources,resources_path,:class => is_active?("resources")%></li>
        <li><%=link_to :Clients,clients_path,:class => is_active?("clients")%></li>
        <li><%=link_to :Role,roleassignments_path,:class => is_active?("roleassignments")%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microgigz</title>
  <%=stylesheet_link_tag "application",:media => "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
  <!--favicon!-->
</head>
<!--background: url('abc.png');opacity: 0.5;z-index:-1;background-repeat: no-repeat!-->

<body>
<%if user_signed_in?%>
    <main id="container" class="container">
       <header id="header" class="row">
         <div class="col-lg-12">
            <%=render "layouts/navbar"%>
         </div>
       </header>
       <section id="content" class="row">
         <% if flash[:notice] %>
             <div class="alert alert-success">
               <p id="notice" ><%= flash[:notice] %></p>
             </div>
           <% elsif flash[:alert] %>
             <div class="alert alert-danger">
               <p id="alert" >
               <%= flash[:alert] %>
               </p>
             </div>
         <% end %>
         <section class="col-lg-8">
             <%=yield%>
         </section>
         <aside class="col-lg-3 visible-lg">
          <%= render_related_links %>
         </aside>
       </section>
      <footer id="footer" class="row">
        <section class="col-lg-12">
          <p>Copyright 	&copy; 2014 :: Microgigz</p>
        </section>
      </footer>
    </main>
<%else%>
    <%=yield%>
<% end %>
</body>
</html>

app/views/resources/_edit_form.html.erb
<%= form_for(@resource,:method=>:put) do |f| %>
    <% if @resource.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this project from being saved:</h2>
          <ul>
            <% @resource.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= f.fields_for @user do |builder| %>
        <div class="display-block">
            <%= builder.label :name %>
            <%= builder.text_field :name,:class=>"form-control"%>
        </div>
        <div class="display-block">
          <%= builder.label :login_id %>
          <%= builder.text_field :login_id,:class=>"form-control"%>
        </div>
        <div class="display-block">
          <%= builder.label :email %>
          <%= builder.text_field :email,:class=>"form-control"%>
        </div>
        <div class="display-block">
          <%= builder.label :telephone %>
          <%= builder.text_field :telephone,:class=>"form-control"%>
        </div>
    <%end%>
    <br/>
    <div class="display-block">
      <%=  submit_tag("Save", :class => 'btn btn-default') %>
      <%= link_to 'Back', resources_path,:class=>"btn btn-default" %>
    </div>
    <br/>
<%end%>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
    <% if @resource.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this project from being saved:</h2>
          <ul>
            <% @resource.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= f.fields_for @user do |builder| %>
        <div class="display-block">
          <b>Name</b>
          <br/>
          <%=builder.text_field :name,:class=>"form-control" %>
        </div>
        <div class="display-block">
          <b>Password</b>
          <br/>
          <%=builder.password_field :password,:class=>"form-control" %>
        </div>
        <div class="display-block">
          <b>Email</b>
          <br/>
          <%=builder.text_field :email,:class=>"form-control" %>
        </div>
        <div class="display-block">
          <b>Login id</b>
          <br/>
          <%=builder.text_field :login_id,:class=>"form-control" %>
        </div>
        <div class="display-block">
          <b>Telephone</b>
          <br/>
          <%=builder.text_field :telephone,:class=>"form-control" %>
        </div>
        <div class="display-block">
          <%=builder.hidden_field :userable_type,:value=>"Resource",:class=>"form-control" %>
        </div>
    <%end%>
    <div class="display-block">
      <%= f.hidden_field :availability,:value=>"Available",:class=>"form-control"%>
    </div>
    <br/>
    <div class="display-block">
      <%=  submit_tag("Save", :class => 'btn btn-default') %>
      <%= link_to 'Back', clients_path,:class=>"btn btn-default" %>
    </div>
    <br/>
<%end%>

app/views/resources/_related_links.html.erb
<h1>Related links of resources</h1>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>
<%= render 'edit_form' %>

app/views/resources/index.html.erb
<%=pageHeader("Resources")%>
<div id="page-container">
  <%i = 0%>
  <%@resources.each do |resource|%>
      <div id="record" lang="<%=i%>" class="row leads" onmouseover="dsiplay_circle(this);" onmouseout="hide_circle(this);">
        <section class="position_relative">
          <p id="title">
            <span id="active">Active</span>
            <%=link_to("#{resource.user.name}",resource_path(id:resource.id))%>
          </p>
          <p id="description">
            <%@user_roles = resource.user.roles%>
            <%@user_roles.each do |i| %>
                <%= link_to "#{i.name}" , roleassignments_path, :style => "color:#696969" %>
            <%end%>
          </p>
          <section id="edit-destroy-link">
            <div class="dropdown">
              <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">
                <img src="/images/settings.png" height="25" id="<%=i%>" onclick="show_menu(this);" width="25"/>
              </a>
              <ul class="dropdown-menu" onmouseout="hide_block(this);" onmouseover="display_block(this);" id="menu<%=i%>"  role="menu" aria-labelledby="dLabel">
                <li><%=link_to('Edit', edit_resource_path(resource))%></li>
                <li><%=link_to('Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' })%></li>
              </ul>
            </div>
          </section>
        </section>
        <div class="clear-both">
        </div>
      </div>
      <hr/>
      <%i = i+1%>
  <%end%>
</div>





















<!--<h1>Listing resources</h1>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% #@resources.each do |resource| %>
  <tr>
    <td><%#=link_to "#{resource.name}",resource_path(resource.id)%></td>
    <td></td>
    <td><%#=resource.name%></td>
    <td><%#= link_to 'Show',resource_path(id:resource.userable_id) %></td>
    <td><%#= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%#= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% #end %>
</table>

<br />

<%#= link_to 'New Resource', new_resource_path %>
!-->

app/views/resources/new.html.erb
<h1>New resource</h1>
<%= render 'form' %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<br/><br/>
<div class="list-group border-margin-client-show">
  <li class="list-group-item border-none">
    <h4 class="list-group-item-heading margin-title">Name</h4>
    <p class="list-group-item-text"><%= @user.name %></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Email</h4>
    <p class="list-group-item-text"><%= @user.email %></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Login id</h4>
    <p class="list-group-item-text">  <%= @user.login_id %></p>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Telephone</h4>
    <p class="list-group-item-text"><%= @user.telephone %></p>
  </li>
  <% if @user.userable_type == "Client" %>
    <li class="list-group-item">
        <h4 class="list-group-item-heading">Company Name</h4>
        <p class="list-group-item-text"><%#=@client.company_name%></p>
    </li>
  <%end%>
  <li class="list-group-item">
    <p class="list-group-item-text">
      <%= link_to 'Edit', edit_resource_path(@resource),:class=>"btn btn-default" %>
      <%= link_to 'Back', resources_path,:class=>"btn btn-default"%>
    </p>
  </li>
</div>